<?php

use Illuminate\Database\Seeder;
use App\Estudiante;

class EstudianteTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Estudiante::create([
            'matricula' => '2015406023',
            'rut' => '9.354.351-3',
            'nombre' => 'Jose',
            'ap_Paterno' => 'Soto',
            'ap_Materno' => 'Lopez',
            'correo' => 'jsoto15@alumnos.utalca.cl',
            'sexo' => 'm',
            'fech_nac' => '03/12/1995',
            'plan' => 16,
            'año_ingreso' => 2015,
            'estado_actual' => 'Regular',
            'comuna' => 'talca',
            'region' => 7,
            'creditos_aprobados' => 100,
            'nivel' => 4,
            'porc_avance' => 35,
            'ult_ptje_prioridad' => '500,23',
            'regular' => 'si',
            'prom_aprobadas' => '5,23',
            'prom_cursados' => '5,34',
            'id_carrera' => 1,
            'num_observaciones' => 0,
        ]);
        Estudiante::create([
            'matricula' => '2015406045',
            'rut' => '13.010.069-4',
            'nombre' => 'Francisco',
            'ap_Paterno' => 'Muñoz',
            'ap_Materno' => 'Jara',
            'correo' => 'fmuñoz15@alumnos.utalca.cl',
            'sexo' => 'm',
            'fech_nac' => '08/10/1996',
            'plan' => 16,
            'año_ingreso' => 2015,
            'estado_actual' => 'Regular',
            'comuna' => 'talca',
            'region' => 7,
            'creditos_aprobados' => 60,
            'nivel' => 3,
            'porc_avance' => 20,
            'ult_ptje_prioridad' => '430,23',
            'regular' => 'si',
            'prom_aprobadas' => '4,23',
            'prom_cursados' => '4,34',
            'id_carrera' => 1,
            'num_observaciones' => 0,
        ]);
        Estudiante::create([
            'matricula' => '2014406235',
            'rut' => '18.342.555-2',
            'nombre' => 'Monica',
            'ap_Paterno' => 'Rodriguez',
            'ap_Materno' => 'Gonzalez',
            'correo' => 'mrodriguez14@alumnos.utalca.cl',
            'sexo' => 'f',
            'fech_nac' => '20/06/1993',
            'plan' => 11,
            'año_ingreso' => 2014,
            'estado_actual' => 'Regular',
            'comuna' => 'rancagua',
            'region' => 6,
            'creditos_aprobados' => 200,
            'nivel' => 7,
            'porc_avance' => 80,
            'ult_ptje_prioridad' => '650,23',
            'regular' => 'si',
            'prom_aprobadas' => '6,10',
            'prom_cursados' => '6,32',
            'id_carrera' => 1,
            'num_observaciones' => 0,
        ]);
        Estudiante::create([
            'matricula' => '2016406235',
            'rut' => '24.504.037-7',
            'nombre' => 'Josefa',
            'ap_Paterno' => 'Barra',
            'ap_Materno' => 'Gonzalez',
            'correo' => 'jbarra16@alumnos.utalca.cl',
            'sexo' => 'f',
            'fech_nac' => '01/12/1997',
            'plan' => 16,
            'año_ingreso' => 2016,
            'estado_actual' => 'Regular',
            'comuna' => 'curico',
            'region' => 7,
            'creditos_aprobados' => 140,
            'nivel' => 3,
            'porc_avance' => 40,
            'ult_ptje_prioridad' => '573,23',
            'regular' => 'si',
            'prom_aprobadas' => '5,86',
            'prom_cursados' => '5,67',
            'id_carrera' => 1,
            'num_observaciones' => 0,
        ]);
        Estudiante::create([
            'matricula' => '2018406235',
            'rut' => '19.161.953-6',
            'nombre' => 'Pedro',
            'ap_Paterno' => 'Contreras',
            'ap_Materno' => 'Ramirez',
            'correo' => 'pcontreras18@alumnos.utalca.cl',
            'sexo' => 'f',
            'fech_nac' => '01/12/1998',
            'plan' => 16,
            'año_ingreso' => 2018,
            'estado_actual' => 'Regular',
            'comuna' => 'curico',
            'region' => 7,
            'creditos_aprobados' => 120,
            'nivel' => 4,
            'porc_avance' => 38,
            'ult_ptje_prioridad' => '546,23',
            'regular' => 'si',
            'prom_aprobadas' => '5,36',
            'prom_cursados' => '4,45',
            'id_carrera' => 1,
            'num_observaciones' => 0,
        ]);
    }
}
